window.COLLAGE_LAYOUT = {
  "generated_at_utc": "2026-02-09T00:42:44.685213+00:00",
  "seed": 42,
  "provider": "gemini",
  "model": "gemini-3-pro-image-preview",
  "canvas": {
    "width": 3072,
    "height": 4350
  },
  "world_image": "images/collage/collage_final3.jpg",
  "input_image": "images/collage/collage_input.png",
  "mask_image": "images/collage/collage_mask.png",
  "projects": [
    {
      "id": "mouthful",
      "title": "Beneath A Hundred Streams",
      "year": "2027",
      "status": "Development",
      "role": "Director",
      "runtime": "TBA",
      "summary": "As AI provides new ways to give voice to the river, its water-hungry infrastructure poses a threat to the same entity it helps us hear.",
      "image": "images/mouthful_still.jpg",
      "url": "mouthfulofriver-film-page.html",
      "x": 1446,
      "y": 99,
      "width": 1470,
      "height": 813,
      "x_pct": 0.47070312,
      "y_pct": 0.02275862,
      "width_pct": 0.47851562,
      "height_pct": 0.18689655,
      "angle": -4.664
    },
    {
      "id": "sik",
      "title": "Spaceman in Kongo",
      "year": "2027",
      "status": "In Production",
      "role": "Producer",
      "runtime": "90 mins",
      "summary": "Two young rocket engineers work on building the first Congolese Space Program.",
      "image": "images/sik_still.png",
      "url": "sik-film-page.html",
      "x": 1617,
      "y": 1431,
      "width": 1413,
      "height": 828,
      "x_pct": 0.52636719,
      "y_pct": 0.32896552,
      "width_pct": 0.45996094,
      "height_pct": 0.19034483,
      "angle": 3.2842
    },
    {
      "id": "mulika",
      "title": "Mulika",
      "year": "2022",
      "status": "Archive",
      "role": "Director",
      "runtime": "14 mins",
      "summary": "An ‘afronaut’ emerges from the wreckage of his spaceship in the volcanic crater of Mount Nyiragongo.",
      "image": "images/Mulika_withlaurels.png",
      "url": "mulika-film-page.html",
      "x": 45,
      "y": 1131,
      "width": 1455,
      "height": 807,
      "x_pct": 0.01464844,
      "y_pct": 0.26,
      "width_pct": 0.47363281,
      "height_pct": 0.18551724,
      "angle": -0.4368
    },
    {
      "id": "sij",
      "title": "Sunday in Japan",
      "year": "2026",
      "status": "In Production",
      "role": "Director",
      "runtime": "85 mins",
      "summary": "“Ugandan Jackie Chan” Sunday creates action scenes drawn from his life as an asylum-seeker in Tokyo.",
      "image": "images/sij_withlaurels.png",
      "url": "sij-film-page.html",
      "x": 45,
      "y": 2379,
      "width": 1500,
      "height": 831,
      "x_pct": 0.01464844,
      "y_pct": 0.54689655,
      "width_pct": 0.48828125,
      "height_pct": 0.19103448,
      "angle": -0.8516
    },
    {
      "id": "broadlistening",
      "title": "Broad Listening",
      "year": "2026",
      "status": "Documentary",
      "role": "Director",
      "runtime": "35 mins",
      "summary": "A sci-fi author turned AI engineer enters Japanese politics, using open-source technology to ask whether digital tools can deepen, rather than damage, democracy.",
      "image": "images/broadlistening_still.jpg",
      "url": "broadlistening-film-page.html",
      "x": 1929,
      "y": 2604,
      "width": 1125,
      "height": 627,
      "x_pct": 0.62792969,
      "y_pct": 0.59862069,
      "width_pct": 0.36621094,
      "height_pct": 0.14413793,
      "angle": -4.7942
    },
    {
      "id": "arakawacats",
      "title": "Arakawa Cats",
      "year": "2024",
      "status": "Completed",
      "role": "Director",
      "runtime": "12 mins",
      "summary": "Finding redemption on the banks of Tokyo’s Arakawa river.",
      "image": "images/arakawacats_still.jpg",
      "url": "arakawacats-film-page.html",
      "x": 267,
      "y": 3387,
      "width": 1581,
      "height": 873,
      "x_pct": 0.08691406,
      "y_pct": 0.77862069,
      "width_pct": 0.51464844,
      "height_pct": 0.20068966,
      "angle": -5.3655
    }
  ],
  "aligned_from": "images/collage/collage_final3.png",
  "aligned_transform": {
    "mode": "manual_crop_remove_apa"
  },
  "frames_source": "images/collage/frames2.png"
};
