services:
  # The Backend (Python Web Service)
  - type: web
    name: copro-backend
    env: python
    plan: free
    region: ohio
    buildCommand: pip install -r backend/requirements.txt && python backend/seed_wrapper.py
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.app.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///backend/coproduction.db
      - key: FRONTEND_URL
        value: "https://www.leonelki.com"
      - key: PYTHONPATH
        value: "backend"
