services:
  # The Backend (Python Web Service)
  - type: web
    name: copro-backend
    env: python
    plan: free
    region: ohio
    buildCommand: cd backend && pip install -r requirements.txt && python seed_data.py && python seed_documents.py
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///backend/coproduction.db
      - key: FRONTEND_URL
        value: "https://www.leonelki.com"
